apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: hub-policy-placement
  namespace: hub-policies
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchLabels:
          # Target managed hubs - they have ACM governance policy framework
          feature.open-cluster-management.io/addon-governance-policy-framework: available
          # Target specific hub
          name: mh-01